# Generated by Django 2.1.7 on 2019-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order_num',
            field=models.IntegerField(default=1, verbose_name='chapter number for ordering purposes'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
